# .goreleaser.yml
builds:
  - main: main.go
  - binary: gogol
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: 386


archive:
  format_overrides:
    - goos: windows
      format: zip