language: go
sudo: required
go:
  - 1.8.3

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libx11-dev -y
  - sudo apt-get install libxcursor-dev -y

script: 
  - go build
  - rm GoGol

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash