language: go
sudo: required
go:
  - 1.8.3


addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - libxrandr-dev
      - libxi-dev


before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script: 
  - go build
  - rm GoGol

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash