language: go
sudo: required
go:
  - 1.8.3


addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - libxrandr-dev
      - libxi-dev
      - xorg-dev


before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - go get github.com/go-gl/gl/v4.1-core/gl
  - go get github.com/go-gl/glfw/v3.2/glfw


script: 
  - go build
  - rm GoGol

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash